### PR TITLE
Manual Hour Entry Added

### PR DESCRIPTION
**Pull request by hirshagarwal**
I added the first part of the primary functionality of the site. If you visit enterHours.html you can take a look. I am still attempting to verify that addition works in every instance. @jamiewitter Do you want to take a look at it? You mentioned that may want to perform some testing, I thought this could be a good place to start.

-- Hirsh

### CODE REVIEW

**Comment by jamiewitter** [comment]
Will do.

**Comment by hirshagarwal** [comment]
@jamiewitter This branch has been closed. But I added a basically identical task in the issues page. If you look there you can see it. When you check this do you mind commenting any problems or closing the issue if you can't find any bugs?

Thanks!

-- Hirsh

**Comment by jamiewitter** [comment]
Definitely

**Comment by hirshagarwal** [comment]
Thank you sir!

**Pull request merged**
